image: bitwalker/alpine-elixir-phoenix:1.6.0

# Cache deps and _build by default
cache:
  paths:
    - _build
    - deps

# Run mix test
test:
  services:
    - postgres:latest
  variables:
    MIX_ENV: ci
    POSTGRES_DB: code_stats_ci
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  before_script:
    - echo 'use Mix.Config' > config/appsignal.exs
    - mix deps.get
  script:
    - mix compile --warnings-as-errors
    - mix test

# Generate ex_doc documenation to gitlab pages
pages:
  only:
    - master@code-stats/code-stats
  before_script:
    - echo 'use Mix.Config' > config/appsignal.exs
    - echo 'use Mix.Config' > config/dev.secret.exs
    - mix deps.get
    - mix compile
  script:
    - mix docs
    - mv doc public
  artifacts:
    paths:
      - public

deploy_beta:
  variables:
    MIX_ENV: prod
    COOKIE: thisisbeta
  only:
    - test-ci@code-stats/code-stats
  tags:
    - code-stats-beta
  script:
    - cp /var/codestats/beta/config/{appsignal,dev.secret,prod.secret}.exs config/
    - mix deps.get
    - mix compile
    - mix release --env=prod
