test:
  image: elixir:latest
  services:
    - postgres:latest
  variables:
    MIX_ENV: ci
    POSTGRES_DB: code_stats_ci
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  before_script:
    - echo 'use Mix.Config' > config/appsignal.exs
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
  script:
    - mix test

pages:
  image: elixir:latest
  before_script:
    - echo 'use Mix.Config' > config/appsignal.exs
    - echo 'use Mix.Config' > config/dev.secret.exs
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
    - mix compile
  script:
    - mix docs
    - mv doc public
  artifacts:
    paths:
      - public
